const UPDATE_MESSAGES = "UPDATE_MESSAGES";
const NEW_MESSAGE = "NEW_MESSAGE";
const POST_MESSAGE = "POST_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";

module.exports = {
  UPDATE_MESSAGES,
  NEW_MESSAGE,
  POST_MESSAGE,
  LIKE_MESSAGE
}